version: "3.6"

services:
  frontend:
    container_name: ${PROJECT_NAME}
    build:
      context: ./_docker
      args:
        - ARCHITECTURE=${ARCHITECTURE}
        - BUILD_PLATFORM=${BUILD_PLATFORM}
        - DOCKER_IMAGE=${DOCKER_IMAGE}
    env_file:
      - ./.env
    ports:
      - "${FE_HOST}:${FE_PORT}:${FE_PORT}"
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
